name: 'Release Label Validator'
description: 'Validate Pull Request Release Labels'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
runs:
  using: "composite"
  steps:
    - name: Pull Request contains 'major' label
      if: contains(github.event.pull_request.labels.*.name, 'major')
      shell: bash
      run: |
          if [[ "${{ github.base_ref }}" == "${{ github.event.repository.default_branch }}" ]]; then
            echo "It is OK to have 'major' label on Pull Request for 'default' branch"
          else
            echo "Label 'major' can NOT be set for 'non-default' branch"
            exit 1
          fi

    - name: Pull Request does not contain 'major' label
      if: "!contains(github.event.pull_request.labels.*.name, 'major')"
      shell: bash
      run: |
          echo "No 'major' label set"
